services:
  affine:
    image: ghcr.io/toeverything/affine:${AFFINE_IMAGE_TAG}
    container_name: affine_server
    depends_on:
      affine_redis:
        condition: service_healthy
      affine_postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - ./affine/uploads:/root/.affine/storage
      - ./affine/config:/root/.affine/config
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${AFFINE_DB_USER}:${AFFINE_DB_PASS}@affine_postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false
    restart: unless-stopped

  affine_migration:
    image: ghcr.io/toeverything/affine:${AFFINE_IMAGE_TAG}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - ./affine/uploads:/root/.affine/storage
      - ./affine/config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${AFFINE_DB_USER}:${AFFINE_DB_PASS}@affine_postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false
    depends_on:
      affine_postgres:
        condition: service_healthy
      affine_redis:
        condition: service_healthy

  affine_redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  affine_postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres
    volumes:
      - ./affine/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${AFFINE_DB_USER}
      POSTGRES_PASSWORD: ${AFFINE_DB_PASS}
      POSTGRES_DB: affine
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "affine", '-d', "affine"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


