services:
  vpn:
    image: qmcgaw/gluetun:${GLUETUN_IMAGE_TAG}
    container_name: vpn_tunnel
    privileged: true
    cap_add:
      - NET_ADMIN
    env_file: 
      - .envs/generic.env
      - .envs/automations/vpn.env
    devices:
      - /dev/net/tun
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: unless-stopped

  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:${QBT_IMAGE_TAG}
    container_name: qbittorrent
    env_file: 
      - .envs/generic.env
      - .envs/automations/qbt.env
    volumes:
      - ./qbt/config:/config
      - ${QBT_TEMP_FOLDER}:/downloads
      - ${SONARR_IMPORT_FOLDER}:/tvdownloads
      - ${RADARR_IMPORT_FOLDER}:/filmdownloads
    # Force all traffic from this container through the VPN container, if available
    network_mode: service:vpn
    # Wait until VPN container is alive and well before starting this container
    depends_on:
      - vpn
    restart: unless-stopped

  sonarr: #TV
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment: .envs/generic.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr/config:/config
      - ${TV_DIR}:/tv
      - ${SONARR_IMPORT_FOLDER}:/downloads
    restart: unless-stopped
    # This service makes regular requests to the QBittorrent container, and 
    # warns when said container is not available. May as well wait until it 
    # exists before starting this container.
    depends_on:
      - qbittorrent

  radarr: #Movies
    image: linuxserver/radarr:latest
    container_name: prowlarr
    environment: .envs/generic.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr/config:/config
      - ${MOVIE_DIR}:/movies
      - ${RADARR_IMPORT_FOLDER}:/downloads
    restart: unless-stopped
    depends_on:
      - qbittorrent

  prowlarr: #Indexer management for Sonarr and Radarr
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment: .envs/generic.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr/config:/config
    restart: unless-stopped

  bazarr: #Subtitles
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment: .envs/generic.env
    volumes:
      - ./bazarr/config:/config
      - ${MOVIE_DIR}:/movies
      - ${TV_DIR}:/tv
    restart: unless-stopped
