include:
  - docker-compose.affine.yml
  - docker-compose.audiobook.yml
  - docker-compose.automations.yml
  - docker-compose.caddy.yml
  - docker-compose.cookbook.yml
  - docker-compose.feedReader.yml
  - docker-compose.gitRepo.yml
  - docker-compose.immich.yml
  - docker-compose.jellyfin.yml
  - docker-compose.landingPage.yml
  - docker-compose.monitoring.yml
  - docker-compose.tools.yml
  - docker-compose.rss.yml

# Declare a custom network, named internal, that all other containers will use to talk to each other.
# This keeps all inter-container communication off the physical network.
networks:
  default:
    name: internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${INTERNAL_SUBNET}
          ip_range: ${INTERNAL_SUBNET}
          gateway: ${INTERNAL_GATEWAY}
